-- script_creacion_tablas.sql

-- Tabla usuario
CREATE TABLE usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    contraseña VARCHAR(100) NOT NULL,
    fecha_registro DATE NOT NULL,
    direccion VARCHAR(200) NOT NULL,
    telefono VARCHAR(20) NOT NULL UNIQUE
);

-- Tabla inventario
CREATE TABLE inventario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR(100) NOT NULL,
    descripcion_producto VARCHAR(255),
    cantidad INT NOT NULL,
    precio DECIMAL(10,2) NOT NULL
);

-- Tabla carrito (pedido)
CREATE TABLE pedido (
    id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    evento_id INT NOT NULL,
    fecha_pedido DATE NOT NULL,
    total_pedido DECIMAL(10,2) NOT NULL,
    metodo_pago_pedido VARCHAR(50),
    direccion_facturacion_pedido VARCHAR(255),
    CONSTRAINT fk_usuario
      FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_evento
      FOREIGN KEY (evento_id) REFERENCES evento(id_evento)
);

-- Tabla evento (necesaria para la FK en pedido)
CREATE TABLE evento (
    id_evento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_evento VARCHAR(100) NOT NULL UNIQUE,
    descripcion_evento VARCHAR(255) NOT NULL,
    fecha_inicio_evento DATE NOT NULL,
    fecha_fin_evento DATE NOT NULL,
    capacidad_maxima_evento INT NOT NULL,
    costo_entrada_evento DECIMAL(10,2) NOT NULL,
    fecha_creacion_evento DATE NOT NULL
);
